apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- with .Values.tags }}
    machine: {{ .machine | default "NA" | upper }}
    rank: {{ .rank }}
    gpu: {{ .gpu }}
  {{- end }}
data:
  Name: {{ .Values.name }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ .Values.infra.region  | upper | quote }}
  current: {{ now | date "2006-01-02" | upper }}
  {{- if eq .Release.Name "zoggy" }}
  release: "one"
  {{- else if eq .Release.Name "ziggy" }}
  release: "two"
  {{- else }}
  release: "three"
  {{- end }}
  Framework used: |-
    {{- range .Values.frameworks }}
    - {{ . | title | quote }}
    {{- end }}
  