apiVersion: apps/v1
kind: Deployment
metadata:
        name: httpd-frontend
        labels:
                name: frontend
spec:
        replicas: 3
        selector:
                matchLabels:
                        name: frontend
        template:
                metadata:
                        labels:
                                name: frontend
                spec:
                        containers:
                                - name: httpd-frontend
                                  image: httpd-alpine

