apiVersion: v1
kind: Pod
metadata:
    name: webapp-pod
spec:
    containers:
            - name: webapp-pod
              image: kodekloud/simple-webapp-mysql
              envFrom:
                - secretRef:
                       name: db-secret
