apiVersion: v1
kind: Pod
metadata:
    name: static-busybox
    labels:
       cmd: ghum
spec:
    containers:
        - name: static-busybox
          image: busybox
          command:
                - sleep
                - "1000"
