apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DiptoChakrabarty/Kubeadmin.git
    targetRevision: HEAD
    path: argocd/yamls
  destination: 
    server: https://kubernetes.default.svc
    namespace: default