apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: development
  source:
    repoURL: https://github.com/DiptoChakrabarty/Kubeadmin.git
    targetRevision: HEAD
    path: argocd/yamls
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true