apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webshook
spec:
  service:
    ports:
      - port: 8085
        targetPort: 8085
  webhook:
    argo-webhook:
      port: "8085"
      endpoint: /trigger
      method: POST