apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxdemo
  labels:
    name: fluxdemo
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxdemo
      app: demo
  template:
    metadata:
      labels:
        name: fluxdemo
        app: demo
    spec:
      containers:
        - name: fluxdemo
          image: nginx
          imagePullPolicy: Never
          ports:
              - containerPort: 80


