apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
     - image: redis
       name: redis-pod
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"