apiVersion: v1
kind: Pod
metadata:
  name: kanikobuild
spec:
  containers:
    - name: kanikobuild
      image: gcr.io/kaniko-project/executor:debug
      args: ["--dockerfile=kaniko-images/workspace/Dockerfile",
            "--context=git://github.com/DiptoChakrabarty/Kubeadmin",
            "--destination=diptochakrabarty/kanikobuild"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: context
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: context
      hostPath:
        path: /home/chuck/Desktop/Projects/Kubeadmin/kaniko-images