apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vault
  name: vault-pvc
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  
