apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
     - image: nginx
       name: nginx-pod
  affinity:
    nodeAffinity: 
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
           - matchExpressions:
               - key: size
                 operator: In
                 values:
                    - large