piVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: app-ingress
   namespace: app-space
   annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   rules:
   - http:
      paths:
      - backend:
          serviceName: wear-service
          servicePort: 8080
        path: /wear
        pathType: ImplementationSpecific
      - backend:
          serviceName: video-service
          servicePort: 8080
        path: /watch
        pathType: ImplementationSpecific