apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app.kubernetes.io/name: vault-config
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = 1
    }
    storage "file" {
      path = "/vault/data"
    }
    ui = true
