apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yml
  - config-configmap.yaml
  - clusterrolebinding.yaml
  - ingress.yml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - ui-service.yaml
commonLabels:
  cluster: minikube
