apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pinku-role-binding
  namespace: argo
subjects:
- kind: User
  name: pinku
  apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: Role
   name: pinku-role
   apiGroup: rbac.authorization.k8s.io